Try exit 1 instead

diff --git a/.github/workflows/ci_publish-neural-network.yml b/.github/workflows/ci_publish-neural-network.yml
--- a/.github/workflows/ci_publish-neural-network.yml
+++ b/.github/workflows/ci_publish-neural-network.yml
@@ -32,8 +32,9 @@ jobs:
         NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
     - name: Error if version already exists
       # if: curl - https://nuget.pkg.github.com/benchiverton/query?q=GingerbreadAI.NeuralNetwork
-      run: echo "::error ::Package version already exists in source"
-      continue-on-error: false
+      run: |
+        echo "::error ::Package version already exists in source"
+        exit 1
       # suffix the package with the run number if building from a PR
     - name: Pack Pre-Release
       if: github.event_name == 'pull_request' && github.event.action != 'closed'
